debug: false

server:
  host: 0.0.0.0
  port: 25565

  compression:
    threshold: 256
    level: -1

logger:
  enabled: false
  fileName: logs/latest.log
  maxSize: 2
  maxAge: 7
  maxBackups: 5
  localTime: false
  compress: true
